### ISSUE TITLE
Compatibility with Prosemirror WYSIWYG editor for DokuWiki

### ISSUE THREAD

**Issue by vic-t** [MrReSc/MindTheDark#10]
Recently, I started using the [Prosemirror WYSIWYG editor](https://www.dokuwiki.org/plugin:prosemirror) in DokuWiki.

The editor uses some sort of color banding in the background. I think the idea is that the two colors used in the band should contrast only very little. Enough for the banding still to be visible but not enough to bother. 

This works fine with the regular DW template. And it works still fine with the light mode of MindTheDark. But when switching to the dark mode, you get some black and white banding which makes it essentially impossible to work in the editor window. 

I did some testing and can confirm that Prosemirror, when in dark mode, uses the "Main background color" as one of the two colors and "Main background color in dark color scheme" as the other. That gives you this impossible kind of banding that makes things illegible. 

Curiously, I could not figure out what the secondary color is in light mode. "Main background color" continues to be one of the two but the second one does not seem to be taken from the list of colors in the template style settings. 

Please let me know if you believe this issue should be reported to ProseMirror rather than here.

By the way, since I prefer to work in the Dark Mode, an easy workaround is to simply set the "Main background color" to something very dark. But it would still be nice to have the ability to toggle.

**Comment by MrReSc** [comment]
First of all, thank you for reporting this and thank you for using MindTheDark.

I think it is neither a problem of MindTheDark nor of the prosemirror editor. I know the problem because I have also tested the editor. However, I decided not to support the editor at that time, as it was (and still is) in beta.
The issue with the background has already been discussed in various places. I think until the editor is out of beta I won't bother with it. Currently, the easiest way is to disable the background in the `conf/userstyle.css` file.

You only have to insert the following line into that file.
```
.ProseMirror{ background: none; }
```
If the file does not yet exist, you can simply create it.

If I remember correctly, it works with the deactivated background for the light and dark theme.

I hope this helps you a little. Basically, you can also use the inspector tool (F12 key) in your browser to determine the CSS selector and adjust other things of the plugin in `userstyle.css`.

**Comment by vic-t** [comment]
Thank you for your quick reply, that helps!

**Comment by grimoben** [comment]
`z-index: 1000;` fixed it :)
