### ISSUE TITLE
Compatibility with Struct Schema Editor

### ISSUE THREAD

**Issue by vic-t** [MrReSc/MindTheDark#11]
The struct plugin for DW offers a schema editor. Unfortunately, when in dark mode, the one column where the configuration is done will have a lot of black text on a dark background, making it difficult to work with. 

Apparently, the directives to blame are in jsoneditor.min.css and look like this:

```
div.jsoneditor-field, div.jsoneditor-value {
    font-family: droid sans mono,consolas,monospace,courier new,courier,sans-serif;
    font-size: 10pt;
    color: #1A1A1A;
}
```

It's not a huge deal, I can just toggle to the light mode and all is visible. But is there anything I can do from my side to make this work with MTD in dark mode?

**Comment by MrReSc** [comment]
As it looks, the `usertyle.css` does not work here. Unfortunately, I don't know why. 
I have added the following:
```
.jsoneditor-schema-error, div.jsoneditor td, div.jsoneditor textarea, div.jsoneditor th, div.jsoneditor-field, div.jsoneditor-value {
    colour: var(--text);
}
```
unfortunately without success (don't forget to press `Ctrl` + `F5` to reload the page).

Basically you can replace the `colour` in the file `jsoneditor.min.css`:
```
colour: var(--text, #1A1A1A);
```
You may have to do this for other selectors as well.
This way you can switch the colours. However, you will lose this change after an update.

**Comment by vic-t** [comment]
@MrReSc Your support is really much appreciated! I guess I understand the general idea of how to change a stylesheet when I should run into such an issue again. Is it documented somewhere what flags (besides `--text`) exist?

**Comment by MrReSc** [comment]
Actually, the `userstyle.css` is intended so that the stylesheet of the plugin does not have to be edited in case of such problems. Remember, with an update the stylesheet of the plugin will be overwritten again! 
Maybe you can find some useful info here: [https://www.dokuwiki.org/devel:css#user_styles](https://www.dokuwiki.org/devel:css#user_styles)

Now to your question. Most of these `--Blafoo` [variables ](https://github.com/MrReSc/MindTheDark/blob/9ad8055b5fa88da40cc6dd5d97b205cddc4b1e21/css/_autocolor.less#L1)are the colors you can set in the Theme Manager. 
Some that I introduced in addition to the [standard ](https://www.dokuwiki.org/devel:style.ini#guaranteed_color_placeholders) variables I have described [here](https://github.com/MrReSc/MindTheDark#changing-styles).

I recommend you to have a look at the web developer tool of your browser. This helps enormously.

I hope you get it working.

**Comment by MrReSc** [comment]
Since I'm pretty sure this is not an MDT problem, I'm closing this issue. If it is, don't hesitate to get back to me.
