### ISSUE TITLE
highlight not working in dark theme

### ISSUE THREAD

**Issue by dfwdraco76** [MrReSc/MindTheDark#12]
DokuWiki 2018.04.22 on my Synology NAS
MindTheDark 2020-12-02

While testing syntax highlighting, I discovered the actual "highlight_lines_extra" feature is not working in the dark theme.

Example code:
`<code bash [enable_line_numbers="true",highlight_lines_extra="2"]>
var de = function() {
	return (typeof(window.de) == 'object') ? window.de : {};
}();
</code>`

Light theme:
![image](https://user-images.githubusercontent.com/30734939/119168749-daf5d680-ba26-11eb-83a0-1ffc48cc47a2.png)

Dark theme:
![image](https://user-images.githubusercontent.com/30734939/119168791-e943f280-ba26-11eb-8b2f-b3736033293a.png)

**Comment by MrReSc** [comment]
It is quite possible that this will not work. I didn't know about this function until now. I'll take a look at it when I get a chance.

**Comment by MrReSc** [comment]
The problem was not `highlight_lines_extra` but `enable_line_numbers="true"`.
I have adjusted it for the dark theme. The update should actually be available.

![grafik](https://user-images.githubusercontent.com/24952268/119223535-56748800-bafa-11eb-9eb2-f013df0a49fd.png)
![grafik](https://user-images.githubusercontent.com/24952268/119223545-63917700-bafa-11eb-9bc6-6c62fa04c67f.png)



I have not tested it on the old DokuWiki version you are using. But it should actually work just like that.

**Comment by dfwdraco76** [comment]
> The problem was not `highlight_lines_extra` but `enable_line_numbers="true"`.
> I have adjusted it for the dark theme. The update should actually be available.
> 
> I have not tested it on the old DokuWiki version you are using. But it should actually work just like that.

Beautiful, THANK YOU!  By the way, I managed to update my DokuWiki even though the latest version isn't available through the Synology package manager.

Thanks again for the quick fix!!
