### ISSUE TITLE
Gap with Struct tables (Struct plugin)

### ISSUE THREAD

**Issue by Anonymous215025** [MrReSc/MindTheDark#6]
When using the Struct plugin (https://www.dokuwiki.org/plugin:struct), there's a bit of gap to the left:

![image](https://user-images.githubusercontent.com/66980022/84726024-2e26f580-af49-11ea-9e0b-a262cdd14c88.png)

Having it left aligned like this would be a good solution.
![image](https://user-images.githubusercontent.com/66980022/84726099-531b6880-af49-11ea-8c64-60acdfc79d22.png)

Thanks for the template, really simple and good design.

**Comment by MrReSc** [comment]
Currently my template only supports the [Note plugin](https://www.dokuwiki.org/plugin:note). Since I have only limited time at the moment, I can't offer support for the struct plugin now.

For a quick solution, you can create / edit the file [userstyle.css](https://www.dokuwiki.org/devel:css#user_styles) to make the struct plugin look good.

It is actually quite simple:

1. open development tools in your browser (usually F12)
2. select the element with the elemet picker
3. copy CSS Selector
4. insert the CSS Selector and edit in userstyle.css
5. save and possibly clear cache from browser and reload page

If you need help, you can report here.
If the plugin looks good with your [userstyle.css](https://www.dokuwiki.org/devel:css#user_styles), you can give me the stylesheet, then I can integrate it.

**Comment by MrReSc** [comment]
@Anonymous215025 Is your wiki public?  Then I can have a look at it and maybe help you.

**Comment by Anonymous215025** [comment]
Hi MrReSc, it is not public. I'll go ahead and give your suggestions a try. Thank you!

**Comment by MrReSc** [comment]
The issue was closed as no proposal was made by the creator.
